# Generated by Django 5.1 on 2024-08-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('deviceName', models.CharField(max_length=100)),
                ('avgBefore', models.FloatField(blank=True, null=True)),
                ('avgAfter', models.FloatField(blank=True, null=True)),
                ('dataSize', models.IntegerField(blank=True, null=True)),
                ('rawData', models.JSONField()),
            ],
        ),
    ]
