# Generated by Django 5.1 on 2024-08-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_devicedata_avgafter_alter_devicedata_avgbefore_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='rawData',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='avgAfter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='avgBefore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='dataSize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
